title: "VECTOR-0 // DOSSIER"
description: "Information structures and digital systems."

classification: "OPEN DOSSIER"
system_id: "VECTOR-0"

plugins:
  - jekyll-remote-theme

remote_theme: sxthumb/neok2-protocol-noir