title: "OPERATIONAL LOGS"
description: "High-density declassified technical index."
classification: "SECRET // EYES ONLY"
system_id: "SYS_REF_882"

plugins:
  - jekyll-remote-theme

remote_theme: sxthumb/neok2-protocol-noir